---
title: "Week 9 maps"
author: "Jordi Parry"
date: "2/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(mapview)

mapviewOptions(fgb = FALSE)

communities <- read_rds("data/communities.RDS")

# Bike station radius map
bikes <- read.csv("comm_density_2021_all.csv") %>% tibble()
bikes <- bikes %>% 
  mutate(community = community %>% str_to_title()) %>% 
  dplyr::select(community, avg_in_2_mi_radius, population)
bikes_map <- left_join(communities, bikes, by = c("community" = "community"))
mapview(bikes_map, zcol = "avg_in_2_mi_radius") 
```


```{r}
# Average availability map
fullridesdaily <- read.csv("divvy_allyrs_daily.csv")%>% 
  mutate(community = community %>% str_to_title()) %>% 
  dplyr::select(community, available_bikes)
fullavailable <- aggregate(
  fullridesdaily$available_bikes, list(fullridesdaily$community),
  FUN = mean)
fullavailable <- fullavailable %>% 'colnames<-'(c("community", "Availability per Station"))
full.Bike.Availability<- left_join(communities, fullavailable, by = c("community" = "community"))
mapview(full.Bike.Availability, zcol = "Availability per Station")
```


```{r}
# Bike availability per hundred thousand people
fullavailability <- left_join(fullavailable, bikes, by = c("community" = "community"))
fullAvailability_per_capita <- left_join(communities, fullavailability, by = c("community" = "community"))
fullAvailability_per_capita$availperhundthous = 100000*fullAvailability_per_capita$`Availability per Station` / fullAvailability_per_capita$population
mapview(fullAvailability_per_capita, zcol = "availperhundthous")
```

